version: '3.7'

services:
  gcsb-connect-cleanarch-database:
     image: postgres:9.5
     restart: always
     environment:  
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
       - POSTGRES_DB=CleanArch
     ports:
       - 5432:5432
     volumes:
       - pgdata:/var/lib/postgresql/data
     networks:
       - gcsb-cleanarch-network

  gcsb.connect.cleanarch.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - 8080:80
    depends_on: 
      - gcsb-connect-cleanarch-database
    networks: 
      - gcsb-connect-cleanarch-network

networks: 
  gcsb-connect-cleanarch-network:   

volumes:
  pgdata:
    